name: 部署到 GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: install
        run: yarn install 

      - name: Build
        run:  yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.Token_For_Love69_Doc_Website }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist