name: 同步到 LuckyServer
on:
  push:
    branches:
      - main
  
  schedule:
    - cron:  '0 20 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 更换 node 版本 
        uses: actions/setup-node@v4
        with:
          node-version: '16.16.0'

      - name: install
        # https://stackoverflow.com/questions/75959563/node-js-err-ossl-evp-unsupported-error-when-running-npm-run-start
        run: yarn install

      - name: Build
        run:  yarn build

      - name: 上传到 LuckyServer
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ipv4.luckykeeper.site
          FTP_USERNAME: love69doc_luckykeeper_site
          FTP_PASSWORD: ${{ secrets.MIRROR_FTP_PS }}
          # port: 21
          LOCAL_DIR: docs/.vuepress/dist
          REMOTE_DIR: /Doc
          ARGS: --delete --transfer-all --exclude=logreport --verbose